# Generated by Django 5.2.5 on 2025-09-10 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adotante",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_adotante", primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.CharField(db_column="nome", max_length=100)),
                ("email", models.EmailField(db_column="email", max_length=100)),
                ("telefone", models.CharField(db_column="telefone", max_length=15)),
                (
                    "preferencia_porte",
                    models.CharField(
                        blank=True,
                        db_column="preferencia_porte",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "preferencia_idade",
                    models.CharField(
                        blank=True,
                        db_column="preferencia_idade",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "preferencia_sexo",
                    models.CharField(
                        blank=True,
                        db_column="preferencia_sexo",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "aceita_doenca_cronica",
                    models.BooleanField(
                        db_column="aceita_doenca_cronica", default=False
                    ),
                ),
                (
                    "aceita_necessidades_especiais",
                    models.BooleanField(
                        db_column="aceita_necessidades_especiais", default=False
                    ),
                ),
                (
                    "possui_outros_animais",
                    models.BooleanField(
                        db_column="possui_outros_animais", default=False
                    ),
                ),
                (
                    "possui_tempo",
                    models.BooleanField(db_column="possui_tempo", default=False),
                ),
            ],
            options={
                "db_table": "adotante",
            },
        ),
        migrations.CreateModel(
            name="EspeciePet",
            fields=[
                (
                    "id_especie_pet",
                    models.AutoField(
                        db_column="id_especie_pet", primary_key=True, serialize=False
                    ),
                ),
                ("especie", models.CharField(db_column="especie", max_length=100)),
            ],
            options={
                "db_table": "especie_pet",
            },
        ),
        migrations.CreateModel(
            name="Ong",
            fields=[
                (
                    "id_ong",
                    models.AutoField(
                        db_column="id_ong", primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.CharField(db_column="nome", max_length=100)),
                (
                    "email",
                    models.EmailField(db_column="email", max_length=100, unique=True),
                ),
                ("cnpj", models.CharField(db_column="cnpj", max_length=15)),
                (
                    "telefone",
                    models.CharField(db_column="telefone", max_length=15, unique=True),
                ),
                ("endereco", models.CharField(db_column="endereco", max_length=255)),
                ("cidade", models.CharField(db_column="cidade", max_length=100)),
                ("estado", models.CharField(db_column="estado", max_length=100)),
            ],
            options={
                "db_table": "ong",
            },
        ),
        migrations.CreateModel(
            name="StatusPet",
            fields=[
                (
                    "id_status_pet",
                    models.AutoField(
                        db_column="id_status_pet", primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Disponível"),
                            (2, "Perdido"),
                            (3, "Falecido"),
                            (4, "Adotado"),
                        ],
                        db_column="status",
                    ),
                ),
            ],
            options={
                "db_table": "status_pet",
            },
        ),
        migrations.CreateModel(
            name="Adocao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_adocao", primary_key=True, serialize=False
                    ),
                ),
                ("data_adocao", models.DateField(db_column="data_adocao")),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Em Andamento"),
                            (2, "Rejeitada"),
                            (3, "Concluída"),
                        ],
                        db_column="status",
                    ),
                ),
                (
                    "adotante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.adotante"
                    ),
                ),
            ],
            options={
                "db_table": "adocao",
            },
        ),
        migrations.AddField(
            model_name="adotante",
            name="preferencia_especie",
            field=models.ForeignKey(
                db_column="preferencia_especie",
                on_delete=django.db.models.deletion.PROTECT,
                to="api.especiepet",
            ),
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id_evento",
                    models.AutoField(
                        db_column="id_evento", primary_key=True, serialize=False
                    ),
                ),
                ("data", models.DateField(db_column="data")),
                (
                    "descricao",
                    models.TextField(blank=True, db_column="descricao", null=True),
                ),
                (
                    "adocao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.adocao"
                    ),
                ),
            ],
            options={
                "db_table": "evento",
            },
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id_pet",
                    models.AutoField(
                        db_column="id_pet", primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.CharField(db_column="nome", max_length=100)),
                ("idade", models.IntegerField(db_column="idade")),
                ("porte", models.CharField(db_column="porte", max_length=50)),
                (
                    "descricao",
                    models.TextField(blank=True, db_column="descricao", null=True),
                ),
                ("foto", models.TextField(blank=True, db_column="foto", null=True)),
                (
                    "doenca_cronica",
                    models.BooleanField(db_column="doenca_cronica", default=False),
                ),
                (
                    "necessidades_especiais",
                    models.BooleanField(
                        db_column="necessidades_especiais", default=False
                    ),
                ),
                (
                    "cuidados_constantes",
                    models.BooleanField(db_column="cuidados_constantes", default=False),
                ),
                (
                    "amigavel_outros_animais",
                    models.BooleanField(
                        db_column="amigavel_outros_animais", default=False
                    ),
                ),
                (
                    "especie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.especiepet"
                    ),
                ),
                (
                    "ong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.ong",
                    ),
                ),
                (
                    "status_pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.statuspet"
                    ),
                ),
            ],
            options={
                "db_table": "pet",
            },
        ),
        migrations.AddField(
            model_name="adocao",
            name="pet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.pet"
            ),
        ),
        migrations.CreateModel(
            name="RacasPet",
            fields=[
                (
                    "id_raca_pet",
                    models.AutoField(
                        db_column="id_raca_pet", primary_key=True, serialize=False
                    ),
                ),
                ("raca", models.CharField(db_column="raca", max_length=100)),
                (
                    "especie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.especiepet"
                    ),
                ),
            ],
            options={
                "db_table": "racas_pet",
            },
        ),
        migrations.AddField(
            model_name="adotante",
            name="preferencia_raca",
            field=models.ForeignKey(
                db_column="preferencia_raca",
                on_delete=django.db.models.deletion.PROTECT,
                to="api.racaspet",
            ),
        ),
        migrations.CreateModel(
            name="Tutor",
            fields=[
                (
                    "id_tutor",
                    models.AutoField(
                        db_column="id_tutor", primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.CharField(db_column="nome", max_length=100)),
                ("cpf", models.CharField(db_column="cpf", max_length=11, unique=True)),
                (
                    "email",
                    models.EmailField(db_column="email", max_length=100, unique=True),
                ),
                (
                    "telefone",
                    models.CharField(db_column="telefone", max_length=15, unique=True),
                ),
                (
                    "ong",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.ong"
                    ),
                ),
            ],
            options={
                "db_table": "tutor",
            },
        ),
        migrations.AddField(
            model_name="pet",
            name="tutor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.tutor",
            ),
        ),
        migrations.AddConstraint(
            model_name="pet",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("ong__isnull", False), ("tutor__isnull", True)),
                    models.Q(("ong__isnull", True), ("tutor__isnull", False)),
                    _connector="OR",
                ),
                name="pet_owner_xor",
            ),
        ),
    ]
