# Generated by Django 5.2.5 on 2025-11-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pet",
            index=models.Index(fields=["especie"], name="pet_especie_idx"),
        ),
        migrations.AddIndex(
            model_name="pet",
            index=models.Index(fields=["raca"], name="pet_raca_idx"),
        ),
        migrations.AddIndex(
            model_name="pet",
            index=models.Index(fields=["porte"], name="pet_porte_idx"),
        ),
        migrations.AddIndex(
            model_name="pet",
            index=models.Index(fields=["sexo"], name="pet_sexo_idx"),
        ),
        migrations.AddIndex(
            model_name="pet",
            index=models.Index(fields=["status_pet"], name="pet_status_idx"),
        ),
        migrations.AddIndex(
            model_name="pet",
            index=models.Index(fields=["tutor"], name="pet_tutor_idx"),
        ),
        migrations.AddIndex(
            model_name="pet",
            index=models.Index(fields=["ong"], name="pet_ong_idx"),
        ),
        migrations.AddIndex(
            model_name="racaspet",
            index=models.Index(fields=["especie"], name="racas_especie_idx"),
        ),
    ]
