# Generated by Django 5.2.5 on 2025-09-16 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adotante",
            name="aceita_doenca_cronica",
        ),
        migrations.RemoveField(
            model_name="adotante",
            name="aceita_necessidades_especiais",
        ),
        migrations.RemoveField(
            model_name="adotante",
            name="possui_outros_animais",
        ),
        migrations.RemoveField(
            model_name="adotante",
            name="possui_tempo",
        ),
        migrations.RemoveField(
            model_name="adotante",
            name="preferencia_especie",
        ),
        migrations.RemoveField(
            model_name="adotante",
            name="preferencia_idade",
        ),
        migrations.RemoveField(
            model_name="adotante",
            name="preferencia_porte",
        ),
        migrations.RemoveField(
            model_name="adotante",
            name="preferencia_raca",
        ),
        migrations.RemoveField(
            model_name="adotante",
            name="preferencia_sexo",
        ),
    ]
