# Generated by Django 5.2.5 on 2025-09-16 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_adotante_aceita_doenca_cronica_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreferenciaAdotante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferencia_porte",
                    models.CharField(
                        blank=True,
                        db_column="preferencia_porte",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "preferencia_idade",
                    models.CharField(
                        blank=True,
                        db_column="preferencia_idade",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "preferencia_sexo",
                    models.CharField(
                        blank=True,
                        db_column="preferencia_sexo",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "aceita_doenca_cronica",
                    models.BooleanField(
                        db_column="aceita_doenca_cronica", default=False
                    ),
                ),
                (
                    "aceita_necessidades_especiais",
                    models.BooleanField(
                        db_column="aceita_necessidades_especiais", default=False
                    ),
                ),
                (
                    "possui_outros_animais",
                    models.BooleanField(
                        db_column="possui_outros_animais", default=False
                    ),
                ),
                (
                    "possui_tempo",
                    models.BooleanField(db_column="possui_tempo", default=False),
                ),
                (
                    "preferencia_ativa",
                    models.BooleanField(db_column="preferencia_ativa", default=True),
                ),
                (
                    "adotante",
                    models.ForeignKey(
                        db_column="adotante",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.adotante",
                    ),
                ),
                (
                    "preferencia_especie",
                    models.ForeignKey(
                        db_column="preferencia_especie",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.especiepet",
                    ),
                ),
                (
                    "preferencia_raca",
                    models.ForeignKey(
                        db_column="preferencia_raca",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.racaspet",
                    ),
                ),
            ],
        ),
    ]
