# Generated by Django 5.2.5 on 2025-09-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_preferenciaadotante"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="idade",
            field=models.IntegerField(
                choices=[(1, "Filhote"), (2, "Adulto"), (3, "Idoso")], db_column="idade"
            ),
        ),
    ]
