# Generated by Django 5.2.5 on 2025-10-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_pet_idade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="porte",
            field=models.TextField(
                choices=[
                    ("Pequeno", "Pequeno"),
                    ("Médio", "Médio"),
                    ("Grande", "Grande"),
                    ("Muito Grande", "Muito Grande"),
                ],
                db_column="porte",
            ),
        ),
    ]
