# Generated by Django 5.2.5 on 2025-10-21 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_pet_porte"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="raca",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.racaspet",
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="sexo",
            field=models.IntegerField(
                choices=[(1, "Macho"), (2, "Fêmea")], db_column="sexo", default=2
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="idade",
            field=models.IntegerField(
                choices=[
                    (1, "Filhote"),
                    (2, "Adulto"),
                    (3, "Idoso"),
                    (4, "Indiferente"),
                ],
                db_column="idade",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="porte",
            field=models.IntegerField(
                choices=[
                    (1, "Pequeno"),
                    (2, "Médio"),
                    (3, "Grande"),
                    (4, "Muito Grande"),
                    (5, "Indiferente"),
                ],
                db_column="porte",
            ),
        ),
        migrations.AlterField(
            model_name="preferenciaadotante",
            name="preferencia_idade",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Filhote"),
                    (2, "Adulto"),
                    (3, "Idoso"),
                    (4, "Indiferente"),
                ],
                db_column="preferencia_idade",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="preferenciaadotante",
            name="preferencia_porte",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Pequeno"),
                    (2, "Médio"),
                    (3, "Grande"),
                    (4, "Muito Grande"),
                    (5, "Indiferente"),
                ],
                db_column="preferencia_porte",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="preferenciaadotante",
            name="preferencia_sexo",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Macho"), (2, "Fêmea")],
                db_column="preferencia_sexo",
                null=True,
            ),
        ),
    ]
