# Generated by Django 5.2.5 on 2025-11-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_pet_raca_pet_sexo_alter_pet_idade_alter_pet_porte_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="idade",
            field=models.IntegerField(
                choices=[(1, "Filhote"), (2, "Adulto"), (3, "Idoso")], db_column="idade"
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="porte",
            field=models.TextField(
                choices=[
                    ("Pequeno", "Pequeno"),
                    ("Médio", "Médio"),
                    ("Grande", "Grande"),
                    ("Muito Grande", "Muito Grande"),
                ],
                db_column="porte",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="sexo",
            field=models.IntegerField(
                choices=[("Macho", "Macho"), ("Fêmea", "Fêmea")],
                db_column="sexo",
                default=2,
            ),
        ),
    ]
