# Generated by Django 5.2.5 on 2025-11-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_pet_idade_alter_pet_porte_alter_pet_sexo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preferenciaadotante",
            name="preferencia_porte",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Pequeno", "Pequeno"),
                    ("Médio", "Médio"),
                    ("Grande", "Grande"),
                    ("Muito Grande", "Muito Grande"),
                    ("Indiferente", "Indiferente"),
                ],
                db_column="preferencia_porte",
                null=True,
            ),
        ),
    ]
