# Generated by Django 5.2.5 on 2025-11-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_preferenciaadotante_preferencia_porte"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="idade",
            field=models.IntegerField(
                choices=[
                    (1, "Filhote"),
                    (2, "Adulto"),
                    (3, "Idoso"),
                    (4, "Indiferente"),
                ],
                db_column="idade",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="porte",
            field=models.IntegerField(
                choices=[
                    (1, "Pequeno"),
                    (2, "Médio"),
                    (3, "Grande"),
                    (4, "Muito Grande"),
                ],
                db_column="porte",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="sexo",
            field=models.IntegerField(
                choices=[(1, "Macho"), (2, "Fêmea")], db_column="sexo", default=2
            ),
        ),
        migrations.AlterField(
            model_name="preferenciaadotante",
            name="preferencia_porte",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Pequeno"),
                    (2, "Médio"),
                    (3, "Grande"),
                    (4, "Muito Grande"),
                    (5, "Indiferente"),
                ],
                db_column="preferencia_porte",
                null=True,
            ),
        ),
    ]
