# Generated by Django 5.2.5 on 2025-11-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_pet_idade_alter_pet_porte_alter_pet_sexo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preferenciaadotante",
            name="preferencia_sexo",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Macho"), (2, "Fêmea"), (3, "Indiferente")],
                db_column="preferencia_sexo",
                null=True,
            ),
        ),
    ]
