# Generated by Django 5.2.5 on 2025-11-22 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_preferenciaadotante_preferencia_sexo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rastreio",
            fields=[
                (
                    "id_rastreio",
                    models.AutoField(
                        db_column="id_rastreio", primary_key=True, serialize=False
                    ),
                ),
                (
                    "estado_rastreio",
                    models.CharField(db_column="estado_rastreio", max_length=100),
                ),
                (
                    "descricao_rastreio",
                    models.TextField(
                        blank=True, db_column="descricao_rastreio", null=True
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(auto_now=True, db_column="data_atualizacao"),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        db_column="id_pet",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.pet",
                    ),
                ),
            ],
            options={
                "db_table": "rastreio",
            },
        ),
    ]
